---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: word-my
spec:
  rules:
  - host: base.local.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8sapp-svc
            port:
              number: 80
  ingressClassName: nginx

