apiVersion: apps/v1
kind: Deployment
metadata:
 name: k8app-deploy
spec:
 selector:
   matchLabels:
     app: frontend
 replicas: 2
 template:
   metadata:
     labels:
       app: frontend     
   spec:
     affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"
     containers:
     - name: k8sapp-httpd
       image: cs24/k8sapp:latest
       ports:
       - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
 name: k8sapp-svc
spec:
 type: LoadBalancer       
 ports:
 - port: 80
   protocol: TCP
   targetPort: 80
 selector:
   app: frontend


